-- Create a table for public profiles (extends Auth)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  role text default 'employee',
  privacy_settings jsonb default '{"share_deep_work": true, "share_burn_rate": true}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for Calendar Events
create table calendar_events (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  microsoft_id text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  is_meeting boolean default false,
  attendees_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table calendar_events enable row level security;
create policy "Users can view own events." on calendar_events for select using (auth.uid() = user_id);
create policy "Users can insert own events." on calendar_events for insert with check (auth.uid() = user_id);
create policy "Users can update own events." on calendar_events for update using (auth.uid() = user_id);

-- Create a table for Weekly Metrics
create table weekly_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  week_start date not null,
  deep_work_hours numeric default 0,
  meeting_hours numeric default 0,
  burn_rate_score numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, week_start)
);
alter table weekly_metrics enable row level security;
create policy "Users can view own metrics." on weekly_metrics for select using (auth.uid() = user_id);
-- Leaders might need a policy to view others' metrics later
